version: "3"
services:
  pg:
    image: postgres:16.1
    container_name: projeto-spring-db
    restart: always
    environment:
     - POSTGRES_DB=projeto-spring-db
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=root
    ports:
     - 5432:5432